### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by r3pwn** [r3pwn/pixel-placer#4]
- [x] remove color picker from sidebar, make popup appear on click w/ info 
- [x] mobile friendly
- [x] canvas zoom & pan
- [x] polling
- [ ] pixel bank
  - [x] max of 5
  - [x] refill one pixel per minute (make it configurable?)
  - [ ] ability to purchase "instant pixels"
- [ ] Toggle UI
- [ ] Scroll Bars for canvas

### Deprecated Ideas
- [ ] Pixels sales
  - [ ] having owners
  - [ ] the ability to be "for sale"
  - [ ] an adjustable price
